FROM python:3.7

ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y libpq-dev musl-dev build-essential python3-dev python3-psycopg2 postgis cron

RUN mkdir /code
WORKDIR /code
ADD ./wofemtech /code/


RUN pip install -r requirements.txt

CMD ["gunicorn", "wofemtech_django.wsgi", "--bind", "0.0.0.0:9933"]
