"""
Django settings for wofemtech_django project.

Generated by 'django-admin startproject' using Django 2.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '=x-f06ra7d+dawr(**g6iut@11wlfacdhu$@5q9-x&l&vx5$uy'
SECRET_KEY = '4771df5a01ad7b55a3854e583fef920798c1fd244f25ca6daceea1ca8b45b7c2c348a2da2f5939d1ae5133ed033587c1d53a732383565c1745b7bc35410f31c4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'wofemtech.Users'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wofemtech',
    "stripe",
    "djstripe",
    "django_crontab",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wofemtech_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
               # make your file entry here.
               'filter_tags': 'wofemtech.templatetags.filter',
            }
        },
    },
]

WSGI_APPLICATION = 'wofemtech_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.postgresql_psycopg2',
         'NAME': 'greenlight_production',
         'USER': 'postgres',
         'PASSWORD': '6f4d548618737994',
         'HOST': 'db',
         'PORT': '5432',
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = (
   
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

admin_email = "thakkarmeet88@gmail.com"

STRIPE_PUBLIC_KEY  = 'pk_test_QWZu5VFjmdC2n1hf2lHkuZXx00aPDjNm5Q'
STRIPE_PRIVATE_KEY  = 'sk_test_51GinlPJkmA3EhPUhKhSz8QsVnV5KDRmW1T2ZNn59lfXkR16X8OLnobmU2AjFBjK2B7EiXqkJgpbEF6q4m2cdA5LT00P6BvodbH'


# STRIPE_TEST_PUBLIC_KEY ='pk_test_XZxFQlCJ3VzSBgSHgFvP66Dq00nXFFBXbo'
# STRIPE_TEST_SECRET_KEY = 'sk_test_37UVcU4AMJpTk8ObPa71WPjB00KpRgdveH'
# STRIPE_LIVE_MODE = False  # Change to True in production
# DJSTRIPE_WEBHOOK_SECRET = "whsec_JP8XGnOKYvdJcp4bP0wyNRhne5ci9abQ"

STRIPE_TEST_PUBLIC_KEY ='pk_test_QWZu5VFjmdC2n1hf2lHkuZXx00aPDjNm5Q'
STRIPE_TEST_SECRET_KEY = 'sk_test_51GinlPJkmA3EhPUhKhSz8QsVnV5KDRmW1T2ZNn59lfXkR16X8OLnobmU2AjFBjK2B7EiXqkJgpbEF6q4m2cdA5LT00P6BvodbH'
STRIPE_LIVE_MODE = False  # Change to True in production
DJSTRIPE_WEBHOOK_SECRET = "whsec_W7PnNAXp1Sy2CKv1hyWgZUoopSF8lShd"

CRONJOBS = [
    ('*/2 * * * *', 'wofemtech.cron.my_cron_job')
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'crmtest071@gmail.com'
EMAIL_HOST_PASSWORD = 'CrmTest!'