# Generated by Django 3.1.2 on 2020-11-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wofemtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
