# Generated by Django 3.1.2 on 2020-11-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofemtech', '0003_auto_20201108_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='forgot_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
