# Generated by Django 3.1.2 on 2020-12-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wofemtech', '0005_auto_20201108_0336'),
        ('wofemtech', '0004_auto_20201108_0619'),
    ]

    operations = [
    ]
