# Generated by Django 3.1.2 on 2020-12-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofemtech', '0007_auto_20201203_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='phone_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
